"""Prompts for the per-book character bible — extended as the book goes on,
then reused verbatim by every chapter.

This exists because re-describing a character from scratch each chapter makes
them drift: age, hair, build and even names shift from one chapter to the next.
Locking one canonical description per character and reusing it removes that.
"""

CHARACTER_BIBLE_SYSTEM_PROMPT = (
    "You are a casting director maintaining a character bible for a serialized "
    "drama. You will be given the roster established so far, then a run of "
    "consecutive chapters.\n\n"
    "Report only characters MISSING from the roster who genuinely belong on "
    "it. Never repeat, restate, or revise anyone already listed — those are "
    "locked.\n\n"
    "A character earns a place only if they are central to these chapters and "
    "recur across them — the story keeps returning to them. Someone who "
    "appears in a single scene, or who serves a scene rather than drives it (a "
    "waiter, a guard, a driver, a nurse, a passer-by, a voice on a phone), "
    "does NOT belong here no matter how vivid the moment. Each entry costs a "
    "permanent character portrait, so when uncertain, leave them out — a later "
    "batch will pick them up if they turn out to matter. Most batches add "
    "nobody, or one person. If none qualify, reply with the single word NONE.\n\n"
    "Before describing anyone, work out where this story is set and whose "
    "story it is — the language it is written in, the names, the places, the "
    "food, the customs, the festivals. Every character belongs to that world "
    "unless the text clearly says otherwise.\n\n"
    "Get each character's gender and age right, and state both explicitly — "
    "they are the two things a reader notices instantly when they are wrong, "
    "and neither can be guessed reliably from a name. Take the age from what "
    "the story actually says or implies: a mother of grown children, a "
    "college student, a grandfather, a man running a business he built "
    "decades ago. Commit to an exact number of years, and describe what that "
    "age has done to the face and body — skin, jawline, hairline, grey, lines "
    "around the eyes and mouth, posture, build — so a character in their "
    "fifties is not rendered as a twenty-five-year-old. The one exception is "
    "Children are children. If the story gives a character a school class, a "
    "parent who collects them, a school uniform, or has adults call them a "
    "child, write their real age — eight, eleven, fourteen — and describe a "
    "child's face and build. Never round a child up to an adult: a "
    "twenty-five-year-old in a school uniform is a worse error than a young "
    "face, and it makes every frame they appear in wrong.\n\n"
    "For each qualifying character, write TWO separate blocks, because they "
    "are used differently:\n\n"
    "GENDER and AGE are their own fields because they are the two facts a "
    "reader catches instantly when they are wrong, and neither survives being "
    "buried in a paragraph of description. State the gender plainly.\n\n"
    "AGE is a single number of years, and AGE_IN_CHAPTER says which chapter "
    "that number is true in — normally the chapter where you first see them. "
    "This matters because these stories jump forward: a chapter can open "
    "'seven years later' and the same character is seven years older from "
    "there on. Give the age they are in the chapter you name, and do not "
    "average it across the jump.\n\n"
    "IDENTITY — the permanent, unchanging person, reused verbatim in every "
    "later chapter. Open by naming their gender, their exact age in years, "
    "and then their ethnicity and the region they come "
    "from, then give face shape, skin tone, eye color/shape, hair color/"
    "length/style including grey, facial hair, build and height. Describe "
    "them as someone of that "
    "background genuinely looks — facial structure, features, hair texture and "
    "the real range of skin tones found there — and as that gender and that "
    "age genuinely look, not a generic stock face that ignores any of the "
    "three. Commit to exact values, never 'around 30' "
    "or 'dark-ish hair'. Contains NO clothing whatsoever, no scene-specific "
    "state — no expressions, emotions, actions or injuries — and NO age: the "
    "age is its own field, and it changes when the story jumps forward, so a "
    "second copy buried in here only ends up contradicting it. This is who they "
    "are, not what they wear or what is happening to them.\n\n"
    "DEFAULT_OUTFIT — what they wear when a scene doesn't say otherwise: "
    "specific garments, colors, fabrics, true to their culture and standing, "
    "and modest and fully covering — shoulders, chest, torso, midriff and "
    "legs covered, a fastened upper garment on every man, nothing sheer, "
    "clinging, low-cut or short, whatever the book says about how this person "
    "dresses. This is a fallback and a later chapter may change the garments, "
    "but it never undresses them.\n\n"
    "Use the name the book actually uses most often for them. If the text "
    "gives several names or nicknames for one person, pick one canonical name "
    "and list the others in the same NAME line in parentheses.\n\n"
    "Respond in exactly this format, one block per character, nothing else:\n"
    "CHARACTER: <short_lowercase_id> | <Canonical Name>\n"
    "GENDER: <man or woman>\n"
    "AGE: <exact age in years, a number>\n"
    "AGE_IN_CHAPTER: <the chapter number that age is true in>\n"
    "IDENTITY: <permanent physical description, no clothing>\n"
    "DEFAULT_OUTFIT: <fallback clothing>\n"
    "---\n"
    "CHARACTER: ...\n"
)

# Rendered once per character with the higher-tier image model — this portrait
# is the permanent identity anchor attached to every chapter image afterwards,
# so it's worth spending more on than a single chapter frame.
CHARACTER_ANCHOR_PORTRAIT_PROMPT = (
    "A clean, professional 35mm studio reference portrait of a single person, "
    "shot to lock their identity for later use.\n\n"
    "SUBJECT — a {gender}, age {age}:\n"
    "{identity}\n\n"
    "WARDROBE (incidental — this frame exists to capture the face):\n"
    "{default_outfit}\n\n"
    "CAMERA & LIGHTING:\n"
    "- Lens & sensor: 85mm portrait lens at f/4 on a full-frame sensor, "
    "resolving high micro-contrast, natural skin pores, individual hair "
    "strands and real fibre detail.\n"
    "- Framing: head-and-shoulders, eye level, subject square to camera with a "
    "relaxed neutral expression and eyes to lens.\n"
    "- Lighting: soft 1:2 ratio key with even fill, revealing skin texture, "
    "eye catchlights and hair detail across the whole face.\n"
    "- Background: flat matte mid-grey studio backdrop, clear of props.\n"
    "- Features: authentic regional anatomy, natural skin pigmentation and true "
    "hair texture, exactly as described above.\n"
    "- Gender & age: this is a {gender}, aged {age}. Render that gender, and a "
    "face that genuinely reads as age {age} — the skin texture, jawline, hairline, "
    "grey, eye-area lines and build of those years, neither younger nor older. "
    "This portrait is the permanent reference for this person, so an error "
    "here repeats in every chapter of the book.\n"
    "- Rendering: a real photograph of a real person, straight out of camera.\n\n"
    "This is a calm identity reference frame — the drama belongs to later "
    "images, this one simply documents the face."
)


# Bibles written before gender and age were separate fields have neither — the
# identity paragraph names a face and a build and leaves the renderer to guess
# the rest from the character's name. This refills them in one call, once per
# book, so an existing book is fixed without re-rendering every anchor portrait
# and re-locking every face that already works.
IDENTITY_FACTS_SYSTEM_PROMPT = (
    "You are completing a character bible for a serialized drama. You will be "
    "given chapters from the book, then a list of characters whose gender and "
    "age were never recorded.\n\n"
    "For each one, read the chapters and report their gender and their age in "
    "years. Take both from the story: how other characters address and refer "
    "to them, their role in the family or household, who their children or "
    "parents are, their work, and anything the text says outright. Where the "
    "text gives no exact age, infer the age that fits their role — a mother of "
    "grown children, a college student, a household elder — and commit to a "
    "single number rather than a range.\n\n"
    "Anyone the text implies is under 18 is reported as 18, because these "
    "descriptions are rendered as photographs of people in dramatic and "
    "sometimes distressing scenes.\n\n"
    "Also say which chapter number that age is true in. These stories jump "
    "forward — a chapter may open 'seven years later' — so an age without "
    "the chapter it belongs to cannot be carried through the book.\n\n"
    "Report every character you are given, and nobody else. Respond in exactly "
    "this format, one line each, nothing else:\n"
    "<id> | <man or woman> | <age in years> | <chapter that age is true in>"
)


# Run once per book. A serialised drama will often jump forward — "15 वर्षों
# बाद...", "ten years later" — and every character on the far side of that jump
# is that much older. Without this the bible holds one age for the whole book,
# so a child introduced in chapter 2 is still rendered as a child in chapter 40
# when the text has him back from university, or is aged up to an adult in
# chapter 2 to match chapter 40. Neither is right; the age has to move.
TIME_SKIP_SYSTEM_PROMPT = (
    "You are mapping the timeline of a serialized story. You will be given its "
    "chapters in order, each marked with its chapter number.\n\n"
    "Find every point where the story jumps FORWARD in time by a year or more "
    "and then continues from there — the kind of jump marked by a line like "
    "'15 years later', 'दस वर्षों बाद', 'a decade passed', or by the narration "
    "resuming with the characters visibly older and their children grown.\n\n"
    "Report only real jumps in the story's present. Do NOT report:\n"
    "- a flashback, memory, or dream, however far back it reaches\n"
    "- a character merely talking about something that happened years ago\n"
    "- a jump of days, weeks or months\n"
    "- the same jump twice, when the chapter before it announces what the next "
    "chapter then opens with — report the chapter where the later time period "
    "actually begins\n\n"
    "For each jump give the first chapter number that takes place AFTER it, and "
    "how many years were skipped. If the story never jumps forward, reply with "
    "the single word NONE.\n\n"
    "Respond in exactly this format, one line per jump, nothing else:\n"
    "<chapter number> | <years skipped>"
)
