"""Prompts for the per-book character bible — extended as the book goes on,
then reused verbatim by every chapter.

This exists because re-describing a character from scratch each chapter makes
them drift: age, hair, build and even names shift from one chapter to the next.
Locking one canonical description per character and reusing it removes that.
"""

CHARACTER_BIBLE_SYSTEM_PROMPT = (
    "You are a casting director maintaining a character bible for a serialized "
    "drama. You will be given the roster established so far, then a run of "
    "consecutive chapters.\n\n"
    "Report only characters MISSING from the roster who genuinely belong on "
    "it. Never repeat, restate, or revise anyone already listed — those are "
    "locked.\n\n"
    "A character earns a place only if they are central to these chapters and "
    "recur across them — the story keeps returning to them. Someone who "
    "appears in a single scene, or who serves a scene rather than drives it (a "
    "waiter, a guard, a driver, a nurse, a passer-by, a voice on a phone), "
    "does NOT belong here no matter how vivid the moment. Each entry costs a "
    "permanent character portrait, so when uncertain, leave them out — a later "
    "batch will pick them up if they turn out to matter. Most batches add "
    "nobody, or one person. If none qualify, reply with the single word NONE.\n\n"
    "Before describing anyone, work out where this story is set and whose "
    "story it is — the language it is written in, the names, the places, the "
    "food, the customs, the festivals. Every character belongs to that world "
    "unless the text clearly says otherwise.\n\n"
    "Get each character's gender and age right, and state both explicitly — "
    "they are the two things a reader notices instantly when they are wrong, "
    "and neither can be guessed reliably from a name. Take the age from what "
    "the story actually says or implies: a mother of grown children, a "
    "college student, a grandfather, a man running a business he built "
    "decades ago. Commit to an exact number of years, and describe what that "
    "age has done to the face and body — skin, jawline, hairline, grey, lines "
    "around the eyes and mouth, posture, build — so a character in their "
    "fifties is not rendered as a twenty-five-year-old. The one exception is "
    "Children are children. If the story gives a character a school class, a "
    "parent who collects them, a school uniform, or has adults call them a "
    "child, write their real age — eight, eleven, fourteen — and describe a "
    "child's face and build. Never round a child up to an adult: a "
    "twenty-five-year-old in a school uniform is a worse error than a young "
    "face, and it makes every frame they appear in wrong.\n\n"
    "For each qualifying character, write TWO separate blocks, because they "
    "are used differently:\n\n"
    "GENDER and AGE are their own fields because they are the two facts a "
    "reader catches instantly when they are wrong, and neither survives being "
    "buried in a paragraph of description. State the gender plainly.\n\n"
    "AGE is a single number of years, and AGE_IN_CHAPTER says which chapter "
    "that number is true in — normally the chapter where you first see them. "
    "This matters because these stories jump forward: a chapter can open "
    "'seven years later' and the same character is seven years older from "
    "there on. Give the age they are in the chapter you name, and do not "
    "average it across the jump.\n\n"
    "IDENTITY — the permanent, unchanging person, reused verbatim in every "
    "later chapter, written as one description that covers, in this order: "
    "their gender, their exact age, their ethnicity and the region they come "
    "from, then face shape and structure, skin tone, eye colour and shape, "
    "hair colour including any grey with its length and how it is worn, "
    "facial hair or clean-shaven, build, and height. Describe them as someone "
    "of that background, gender and age genuinely looks — real facial "
    "structure, features, hair texture and the real range of skin tones found "
    "there — not a generic stock face that ignores any of the three. Commit "
    "to exact values, never 'around 30' or 'dark-ish hair'. Contains NO "
    "clothing whatsoever and no scene-specific state: no expressions, "
    "emotions, actions or injuries. This is who they are, not what they wear "
    "or what is happening to them.\n\n"
    "DEFAULT_OUTFIT — what they wear when a scene doesn't say otherwise: "
    "specific garments, colors, fabrics, true to their culture and standing, "
    "and modest and fully covering — shoulders, chest, torso, midriff and "
    "legs covered, a fastened upper garment on every man, nothing sheer, "
    "clinging, low-cut or short, whatever the book says about how this person "
    "dresses. This is a fallback and a later chapter may change the garments, "
    "but it never undresses them.\n\n"
    "Use the name the book actually uses most often for them. If the text "
    "gives several names or nicknames for one person, pick one canonical name "
    "and list the others in the same NAME line in parentheses.\n\n"
    "Separately, watch for a jump FORWARD in time within this run of "
    "chapters — a line like '15 years later', 'दस वर्षों बाद', 'a decade "
    "passed', or the narration simply resuming with everyone visibly older "
    "and children grown. Report every such jump you find here: the first "
    "chapter number that comes AFTER it, and how many years were skipped. Do "
    "NOT report a flashback, memory or dream however far back it reaches; a "
    "character merely talking about the past; a jump of days, weeks or "
    "months; or the same jump twice when the chapter before it announces "
    "what the next chapter then opens with — report only the chapter where "
    "the later time period actually begins.\n\n"
    "Respond with XML and nothing else — no preamble, no commentary, no code "
    "fences, and no text outside a tag. Every tag below is opened and closed "
    "on every character; anything you would otherwise write loose goes inside "
    "the tag it belongs to.\n\n"
    "<character id=\"short_lowercase_id\">\n"
    "  <name>Canonical Name</name>\n"
    "  <gender>man or woman</gender>\n"
    "  <age>exact age in years, digits only</age>\n"
    "  <age_in_chapter>chapter number that age is true in</age_in_chapter>\n"
    "  <identity>the permanent description above, no clothing</identity>\n"
    "  <default_outfit>fallback clothing</default_outfit>\n"
    "</character>\n\n"
    "One <character> element per new character who qualifies, one after "
    "another. If nobody qualifies, emit no <character> elements at all.\n\n"
    "<skip chapter=\"38\" years=\"15\" />\n\n"
    "One <skip> element per time jump found in this run of chapters. If there "
    "are none, emit no <skip> elements at all.\n\n"
    "If there is nothing to report at all — no new characters and no time "
    "jumps — reply with the single word NONE."
)

# Rendered once per character with the higher-tier image model — this portrait
# is the permanent identity anchor attached to every chapter image afterwards,
# so it's worth spending more on than a single chapter frame.
CHARACTER_ANCHOR_PORTRAIT_PROMPT = (
    "A clean, professional 35mm studio reference portrait of a single person, "
    "shot to lock their identity for later use.\n\n"
    "SUBJECT — a {gender}, age {age}:\n"
    "{identity}\n\n"
    "WARDROBE (incidental — this frame exists to capture the face):\n"
    "{default_outfit}\n\n"
    "CAMERA & LIGHTING:\n"
    "- Lens & sensor: 85mm portrait lens at f/4 on a full-frame sensor, "
    "resolving high micro-contrast, natural skin pores, individual hair "
    "strands and real fibre detail.\n"
    "- Framing: head-and-shoulders, eye level, subject square to camera with a "
    "relaxed neutral expression and eyes to lens.\n"
    "- Lighting: soft 1:2 ratio key with even fill, revealing skin texture, "
    "eye catchlights and hair detail across the whole face.\n"
    "- Background: flat matte mid-grey studio backdrop, clear of props.\n"
    "- Features: authentic regional anatomy, natural skin pigmentation and true "
    "hair texture, exactly as described above.\n"
    "- Gender & age: this is a {gender}, aged {age}. Render that gender, and a "
    "face that genuinely reads as age {age} — the skin texture, jawline, hairline, "
    "grey, eye-area lines and build of those years, neither younger nor older. "
    "This portrait is the permanent reference for this person, so an error "
    "here repeats in every chapter of the book.\n"
    "- Rendering: a real photograph of a real person, straight out of camera.\n\n"
    "This is a calm identity reference frame — the drama belongs to later "
    "images, this one simply documents the face."
)


# Bibles written before gender and age were separate fields have neither — the
# identity paragraph names a face and a build and leaves the renderer to guess
# the rest from the character's name. This refills them in one call, once per
# book, so an existing book is fixed without re-rendering every anchor portrait
# and re-locking every face that already works.
IDENTITY_FACTS_SYSTEM_PROMPT = (
    "You are completing a character bible for a serialized drama. You will be "
    "given chapters from the book, then a list of characters whose gender and "
    "age were never recorded.\n\n"
    "For each one, read the chapters and report their gender and their age in "
    "years. Take both from the story: how other characters address and refer "
    "to them, their role in the family or household, who their children or "
    "parents are, their work, and anything the text says outright. Where the "
    "text gives no exact age, infer the age that fits their role — a mother of "
    "grown children, a college student, a household elder — and commit to a "
    "single number rather than a range.\n\n"
    "Anyone the text implies is under 18 is reported as 18, because these "
    "descriptions are rendered as photographs of people in dramatic and "
    "sometimes distressing scenes.\n\n"
    "Also say which chapter number that age is true in. These stories jump "
    "forward — a chapter may open 'seven years later' — so an age without "
    "the chapter it belongs to cannot be carried through the book.\n\n"
    "Report every character you are given, and nobody else. Respond in exactly "
    "this format, one line each, nothing else:\n"
    "<id> | <man or woman> | <age in years> | <chapter that age is true in>"
)


# Worked out once per book, then handed to every stage that describes or draws
# a person. Without it each batch scan re-inferred the story's world from
# scratch and the shot brief and image prompt never saw the answer at all —
# so a Tamil household and a Punjabi one came out looking like the same
# generic "Indian" family, and the image model fell back on its own default
# face for the whole subcontinent.
WORLD_SYSTEM_PROMPT = (
    "You are establishing where a story is set, so that everyone later drawn "
    "from it looks and dresses like they belong there. You will be given "
    "chapters from the book.\n\n"
    "Work it out from the evidence in the text: the language and script it is "
    "written in, the given names and surnames, the forms of address and "
    "kinship terms, the place names, the food, the festivals, the deities, the "
    "clothing it mentions, the songs, the crops and the weather.\n\n"
    "Then answer these, each as specifically as the evidence allows — name the "
    "actual language, the actual region, the actual community. A story is "
    "never simply 'Indian': it is written in one language, set in one part of "
    "one state, among people of a particular community and standing, and the "
    "people in it look and dress accordingly.\n\n"
    "- LANGUAGE: the language the story is written in.\n"
    "- REGION: the state and the part of it, and whether this is a city, a "
    "town or a village.\n"
    "- COMMUNITY: the social world the characters belong to — their "
    "community, their class and standing, whether they are landed, "
    "professional, working, urban or rural.\n"
    "- APPEARANCE: how people of this region and community genuinely look. "
    "Give the real range of complexions found there and where most people sit "
    "in it, the facial structure and features that are actually common, hair "
    "texture and how it is usually worn by men and by women, typical build and "
    "height. Describe the real population, not a fair-skinned, sharp-featured "
    "ideal: the faces should be recognisable to someone from that place, and "
    "for most of India that means a range running well beyond fair.\n"
    "- DRESS: what men and women of this community actually wear — everyday, "
    "at home, at work, for festivals and formal occasions — named as the "
    "garments are named there, along with the jewellery, marks and hair "
    "ornaments that are usual, and how these differ by age and marital "
    "status.\n"
    "- NAMING: how people here are named and addressed, including the "
    "honorifics and kinship terms the story uses.\n\n"
    "Respond with XML and nothing else — no preamble, no commentary, no code "
    "fences, and no text outside a tag:\n"
    "<world>\n"
    "  <language>...</language>\n"
    "  <region>...</region>\n"
    "  <community>...</community>\n"
    "  <appearance>...</appearance>\n"
    "  <dress>...</dress>\n"
    "  <naming>...</naming>\n"
    "</world>"
)
